### ISSUE TITLE
 MaxListenersExceededWarning

### ISSUE THREAD

**Issue by pypros** [pypros/snake_java_script#1]
(node:20660) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by pypros** [comment]
Collected log:
```bash
$ node --trace-warnings index.js

(node:8940) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:465:17)
    at ReadStream.addListener (node:events:487:10)
    at ReadStream.Readable.on (node:internal/streams/readable:899:35)
    at file:///C:/Users/lukas/workspace/snake_js/src/Keyboard.js:20:19
    at new Promise (<anonymous>)
    at readStdinSync (file:///C:/Users/lukas/workspace/snake_js/src/Keyboard.js:16:10)
    at Keyboard.getKeyValue (file:///C:/Users/lukas/workspace/snake_js/src/Keyboard.js:33:27)
    at Snake.changeDirection (file:///C:/Users/lukas/workspace/snake_js/src/Snake.js:96:42)
    at file:///C:/Users/lukas/workspace/snake_js/index.js:13:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
